### ISSUE TITLE
401 authentication failed error during OAuth dance

### ISSUE THREAD

**Issue by aeden** [dnsimple/addon-heroku#19]
```
2017-02-17T09:29:21.121860+00:00 app[web.1]: 09:29:21.121 request_id=898060ff-33e1-4145-9946-bc6dcfa47d22 [info] GET /dnsimple/callback
2017-02-17T09:29:21.397337+00:00 app[web.1]: %Dnsimple.RequestError{http_response: %HTTPoison.Response{body: "{\"message\":\"Authentication failed\"}",
2017-02-17T09:29:21.397355+00:00 app[web.1]:   headers: [{"Server", "nginx"}, {"Date", "Fri, 17 Feb 2017 09:29:21 GMT"},
2017-02-17T09:29:21.397356+00:00 app[web.1]:    {"Content-Type", "application/json; charset=utf-8"},
2017-02-17T09:29:21.397357+00:00 app[web.1]:    {"Transfer-Encoding", "chunked"}, {"Connection", "keep-alive"},
2017-02-17T09:29:21.397357+00:00 app[web.1]:    {"X-RateLimit-Limit", "30"}, {"X-RateLimit-Remaining", "30"},
2017-02-17T09:29:21.397358+00:00 app[web.1]:    {"X-RateLimit-Reset", "1487327361"}, {"Cache-Control", "no-cache"},
2017-02-17T09:29:21.397359+00:00 app[web.1]:    {"X-Request-Id", "df184244-2664-4d9e-8c3b-64c85cc48a0f"},
2017-02-17T09:29:21.397359+00:00 app[web.1]:    {"X-Runtime", "0.004851"}, {"X-Content-Type-Options", "nosniff"},
2017-02-17T09:29:21.397360+00:00 app[web.1]:    {"X-Download-Options", "noopen"}, {"X-Frame-Options", "DENY"},
2017-02-17T09:29:21.397361+00:00 app[web.1]:    {"X-XSS-Protection", "1; mode=block"}], status_code: 401},
2017-02-17T09:29:21.397361+00:00 app[web.1]:    {"X-Permitted-Cross-Domain-Policies", "none"},
2017-02-17T09:29:21.397362+00:00 app[web.1]:  message: "HTTP 401: Authentication failed"}
2017-02-17T09:29:21.397985+00:00 app[web.1]: 09:29:21.397 request_id=898060ff-33e1-4145-9946-bc6dcfa47d22 [info] Sent 500 in 275ms
2017-02-17T09:29:21.399579+00:00 app[web.1]: 09:29:21.399 [error] #PID<0.1360.0> running HerokuConnector.Endpoint terminated
2017-02-17T09:29:21.399581+00:00 app[web.1]: Server: addon-heroku-connector.herokuapp.com:80 (http)
2017-02-17T09:29:21.399582+00:00 app[web.1]: Request: GET /dnsimple/callback?code=MyAWc9N9VkMmJCNrUPvWSgB5en1xftEN&state=K_lMDq4k
2017-02-17T09:29:21.399586+00:00 app[web.1]:     ** (RuntimeError) Failed to create webhook: %Dnsimple.RequestError{http_response: %HTTPoison.Response{body: "{\"message\":\"Authentication failed\"}", headers: [{"Server", "nginx"}, {"Date", "Fri, 17 Feb 2017 09:29:21 GMT"}, {"Content-Type", "application/json; charset=utf-8"}, {"Transfer-Encoding", "chunked"}, {"Connection", "keep-alive"}, {"X-RateLimit-Limit", "30"}, {"X-RateLimit-Remaining", "30"}, {"X-RateLimit-Reset", "1487327361"}, {"Cache-Control", "no-cache"}, {"X-Request-Id", "df184244-2664-4d9e-8c3b-64c85cc48a0f"}, {"X-Runtime", "0.004851"}, {"X-Content-Type-Options", "nosniff"}, {"X-Download-Options", "noopen"}, {"X-Frame-Options", "DENY"}, {"X-Permitted-Cross-Domain-Policies", "none"}, {"X-XSS-Protection", "1; mode=block"}], status_code: 401}, message: "HTTP 401: Authentication failed"}
2017-02-17T09:29:21.399582+00:00 app[web.1]: ** (exit) an exception was raised:
2017-02-17T09:29:21.399587+00:00 app[web.1]:         (heroku_connector) web/gateways/dnsimple.ex:143: HerokuConnector.Dnsimple.create_webhook/2
2017-02-17T09:29:21.399588+00:00 app[web.1]:         (heroku_connector) web/controllers/dnsimple_oauth_controller.ex:1: HerokuConnector.DnsimpleOauthController.action/2
2017-02-17T09:29:21.399588+00:00 app[web.1]:         (heroku_connector) web/controllers/dnsimple_oauth_controller.ex:49: HerokuConnector.DnsimpleOauthController.create/2
2017-02-17T09:29:21.399589+00:00 app[web.1]:         (heroku_connector) web/controllers/dnsimple_oauth_controller.ex:1: HerokuConnector.DnsimpleOauthController.phoenix_controller_pipeline/2
2017-02-17T09:29:21.399590+00:00 app[web.1]:         (heroku_connector) lib/heroku_connector/endpoint.ex:1: HerokuConnector.Endpoint.instrument/4
2017-02-17T09:29:21.399592+00:00 app[web.1]:         (heroku_connector) web/router.ex:1: HerokuConnector.Router.do_call/2
2017-02-17T09:29:21.399591+00:00 app[web.1]:         (heroku_connector) lib/phoenix/router.ex:261: HerokuConnector.Router.dispatch/2
2017-02-17T09:29:21.399593+00:00 app[web.1]:         (heroku_connector) lib/heroku_connector/endpoint.ex:1: HerokuConnector.Endpoint.phoenix_pipeline/1
```

**Comment by weppos** [comment]
![screen recording 2017-04-21 at 09 03 am](https://cloud.githubusercontent.com/assets/5387/25266493/999974a0-2671-11e7-8df4-e3f8e7ca9905.gif)
